INSERT INTO PUBLIC.USER (ID, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, IS_ENABLED, PASSWORD, USERNAME) VALUES (1, true, true, true, true, '$2a$10$gLm1ImV7ymnn/3c.H00ue.lYt.Q9LO0dOFTPTATjtcOvOFJrdTysW', 'petro');
INSERT INTO PUBLIC.USER (ID, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, IS_ENABLED, PASSWORD, USERNAME) VALUES (2, true, true, true, true, '$2a$10$ZFKXBIIJk15AXtkn7bRsEu.XDXcKUi8v/CXHBy0OzX0Bsf7O02YbS', 'vendigo');

INSERT INTO PUBLIC.USER_GRANTED_AUTHORITY (ID, AUTHORITY) VALUES (1, 'ROLE_ADMIN');
INSERT INTO PUBLIC.USER_GRANTED_AUTHORITY (ID, AUTHORITY) VALUES (2, 'ROLE_USER');

INSERT INTO PUBLIC.USER_AUTHORITIES (USER_ID, AUTHORITIES_ID) VALUES (1, 2);
INSERT INTO PUBLIC.USER_AUTHORITIES (USER_ID, AUTHORITIES_ID) VALUES (2, 2);
INSERT INTO PUBLIC.USER_AUTHORITIES (USER_ID, AUTHORITIES_ID) VALUES (2, 1);